### ISSUE TITLE
Titelseite

### ISSUE THREAD

**Issue by JaMeZ-B** [JaMeZ-B/LaTeX-wwu-old#9]
Nachdem ich jetzt schon von @moregrey  und von @phist91 gehört habe, dass die neue Titelseite mit den drei doch relativ großen QR-Codes etwas überladen ist, will ich hier mal eine kleine Diskussion über die Titelseite starten … 

Ich sehe durchaus ein, dass die Titelseite so etwas überfüllt ist. Von daher werde ich die QR-Codes in meiner Master-Datei wohl auf eine extra Seite auslagern, wo dann auch noch der QR-Code der Vorlesungsseite landet.

Nur mit der Titelüberschrift und so weiter finde ich die Titelseite allerdings wiederum etwas zu leer. Was habt ihr für Ideen, was man da stattdessen an Illustrationen oder Ähnlichem hintun könnte?

Hier sind meine Ideen (für die ich sogar teilweise Pixelgrafiken akzeptieren würde):
- Bilder berühmter Mathematiker, deren Erkenntnisse entscheidend sind für das Fach (zum Beispiel Hilbert für FunkAna oder Galois für Einführung in die Algebra – wobei das nur für die Vorlesung bei Bartels passend wäre…)
- Coole Zeichnungen, die sowieso schon drin sind, wie zB der Torus für AnaTopGeo

**Comment by phist91** [comment]
An den zweiten Vorschlag hatte ich auch schon für Zahlentheorie gedacht, hatte nur noch nicht entschieden, was ich nehmen soll (vermutlich wird's ein Plot der \varphi-Funktion). Bevorzuge also definitiv den zweiten Vorschlag.

**Comment by moregrey** [comment]
Ich wüsste jetzt gar nicht, inwiefern man da auf Bildrechte achten müsste.. Zeichnung finde ich daher dann auch besser.

**Comment by JaMeZ-B** [comment]
Ich bevorzuge den auch … aber es wird in einigen Fächern echt schwer :D 
An die Bildrechte hab ich noch gar nicht gedacht, wobei ich mir vorstellen kann, dass man historische Bilder von Mathematikern auch gut mit passenden Lizenzen finden sollte.
